name: Auto Commit

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make changes
        run: |
          echo "Last updated: $(date)" >> log.txt

      - name: Commit & Push
        run: |
          git config user.name "kishansaaai"
          git config user.email "222060771+kishansaaai@users.noreply.github.com"
          git add .
          git commit -m "Auto commit: $(date)" || exit 0
          git push
